import Head from "next/head";
import Link from "next/link";
import Image from "next/image";

import styles from "../../styles/Currency.module.css";

export default function Currency() {
  return (
    <div className={styles.container}>
      <Head>
        <title>CryptoBoard - Track your performance</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Link href="/">
          <a>Back to home</a>
        </Link>
        <h1>Currency</h1>
        <Image
          src="/images/cosmos-atom-logo.png" // Route of the image file
          height={144} // Desired size with correct aspect ratio
          width={144} // Desired size with correct aspect ratio
          alt="Your Name"
        />
      </main>
    </div>
  );
}
