import Head from "next/head";
import styles from "../styles/Home.module.css";
import axios from "axios";
import { Component } from 'react'

import CurrencyTable from '../components/CurrencyTable'

class Home extends Component {

  constructor(props) {
    super(props);
    this.state = {
      currencies: [],
      funds: 0,
      invested: 0,
      gains: 0,
      invests: {
        "ETH": 835,
        "EGLD": 192,
        "ATOM": 150,
        "BNB": 125,
        "ENJ": 155,
        "COTI": 100,
        "KDA": 100,
        "DYDX": 50,
        "ERN": 50,
        "NEAR": 50,
        "SOL": 0,
      }
    };
    this.loadData = this.loadData.bind(this);
  }

  componentDidMount() {
    this.loadData()
  }

  async loadData() {
    let data = await axios.get("api/portfolio").then(res => res.data)

    if (data && data.hasOwnProperty('currencies')) {

      let fund = 0;
      let totalInvested = Object.keys(this.state.invests).reduce((accumVariable, curValue) => {
        return accumVariable + this.state.invests[curValue]
      }, 0);

      data.currencies.forEach((currency) => {
        currency.invest = this.state.invests.hasOwnProperty(currency.name) ? this.state.invests[currency.name] : 0;
        currency.gain = Math.round(currency.value - currency.invest);
        fund += currency.value;
      });

      fund = Math.round(fund * 100) / 100
      this.setState({ currencies: data.currencies, funds: fund, invested: totalInvested, gains: Math.round(fund - totalInvested) });
    }

  }

  render() {
    return (
      <div className={styles.container}>
        <Head>
          <title>CryptoBoard - Track your performance</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className="flex flex-col justify-center items-center gap-y-10 p-12">
          <h1 className="text-5xl font-bold underline">Crypto Board</h1>
          <div className='cursor-pointer' onClick={this.loadData}>reload datas</div>
          <div className='flex flex-row gap-x-5'>
            <div>Current value : {this.state.funds}$</div>
            <div>Invested value : {this.state.invested}$</div>
            <div>gains : {this.state.gains}$</div>
          </div>
          <CurrencyTable currencies={this.state.currencies} columns={[
            {
              name: 'Name',
              selector: row => row.name,
              sortable: true,
            },
            {
              name: 'Quantity',
              selector: row => row.total,
              sortable: true,
            },
            {
              name: 'Average',
              selector: row => row.average,
              sortable: true,
            },
            {
              name: 'Value',
              selector: row => row.value,
              sortable: true,
            },
            {
              name: 'Invest',
              selector: row => row.invest,
              sortable: true,
            },
            {
              name: 'Gain',
              selector: row => row.gain,
              sortable: true,
            },
          ]}></CurrencyTable>
        </main>

        <footer className={styles.footer}></footer>
      </div >
    )
  };
}

export default Home